# Site settings
title: Shane Lindsay
email: S.Lindsay@hull.ac.uk
description: > # this means to ignore newlines until "baseurl:"
  Psychology lecturer at the University of Hull.
  Studying language, cognition and the brain
  
# baseurl: "/" # the subpath of your site, e.g. /blog/
url: "https://shanelindsay.github.io" # the base hostname & protocol for your site
twitter_username: shanelindsay
github_username:  shanelindsay
facebook: shanelindsay
#avatar: https://raw.githubusercontent.com/barryclark/jekyll-now/master/images/jekyll-logo.png
university_profile_url: "https://www.hull.ac.uk/staff-directory/shane-lindsay"
worktribe_url: "https://hull-repository.worktribe.com/person/315748/shane-lindsay/outputs"
google_scholar_url: "https://scholar.google.co.uk/citations?user=tTSUv-sAAAAJ&hl=en"
researchgate_url: "https://www.researchgate.net/profile/Shane_Lindsay"
lab_name: "CogLang"
short_description: "Language, memory, and cognition"

permalink: /blog/:year/:month/:title.html

disqus:
    shortname: shanelindsay

plugins:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-redirect-from

# Build settings
markdown: kramdown
theme: minima

defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  - scope:
      path: "css/"
    values:
      layout: null

tags:
- web
- teaching
- research

header_pages:
  - about.md
  - research.md
  - publications.md
  - research-students.md
  - lab.md
  - teaching.md

timezone: Europe/London
author: Shane Lindsay
logo: /images/me.jpg
