# Site settings
title: Shane Lindsay
email: shanelindsay @ gmail com
description: > # this means to ignore newlines until "baseurl:"
  Psychology lecturer at the University of Hull.
  Studying language, cognition and the brain
  
# baseurl: "/" # the subpath of your site, e.g. /blog/
url: "https://shanelindsay.github.io" # the base hostname & protocol for your site
# twitter_username: shanelindsay
#github_username:  shanelindsay
facebook: shanelindsay
#avatar: https://raw.githubusercontent.com/barryclark/jekyll-now/master/images/jekyll-logo.png

permalink: /blog/:year/:month/:title.html

gems:
  - jekyll-sitemap

# Build settings
markdown: kramdown
theme: minima

tags:
- web
- teaching
- research
